package com.example.appchamadosjava.enums;

public enum ProblemEnum {

    // SERVIÇOS
    SERVICOS_INTERNET,
    SERVICOS_TELEFONIA,
    SERVICOS_VOIP,

    // SISTEMA
    SISTEMA_LENTIDAO,
    SISTEMA_OFFLINE,

    // EQUIPAMENTOS
    EQUIPAMENTO_COMPUTADOR,
    EQUIPAMENTO_IMPRESSORA,
    EQUIPAMENTO_COLETOR,
    EQUIPAMENTO_TELEFONE,
    EQUIPAMENTO_LEITOR,

    // PERIFÉRICOS
    PERIFERICO_MOUSE,
    PERIFERICO_TECLADO,
    PERIFERICO_MONITOR,

    PLATAFORMA_SHOPPE,
    PLATAFORMA_SHEIN

}
