package com.example.appchamadosjava.models.enums;

public enum ProblemEnum {

    // SERVICOS
    SERVICOS_INTERNET,
    SERVICOS_TELEFONIA,
    SERVICOS_VOIP,

    // SISTEMA
    SISTEMA_LENTIDAO,
    SISTEMA_OFFLINE,

    // EQUIPAMENTOS
    EQUIPAMENTO_COMPUTADOR,
    EQUIPAMENTO_IMPRESSORA,
    EQUIPAMENTO_COLETOR,
    EQUIPAMENTO_TELEFONE,
    EQUIPAMENTO_LEITOR,

    // PERIFERICOS
    PERIFERICO_MOUSE,
    PERIFERICO_TECLADO,
    PERIFERICO_MONITOR,

    // PLATAFORMAS
    PLATAFORMA_SHOPEE,
    PLATAFORMA_SHEIN

}
